### ISSUE TITLE
Mythic+ tracking feature not completely working.

### ISSUE THREAD

**Issue by Kaymoney** [Skamer/Eska-Tracker#11]
The Mythic+ tracking feature seems to be mostly broken. The picture of the dungeon is no longer there, the timer shows x:xx/0:00 instead of how much time is allocated to complete the dungeon. No affix showing, no battle rez number. Although the death and boss trackers are working.

No errors reporting back. 

![0gjcne8](https://user-images.githubusercontent.com/41488623/43048252-51e15a8e-8d99-11e8-8421-db4318594f74.png)

Using EskaTracker v1.0.18-beta

Using PLoop v223
Using Scorpio v022

**Comment by Skamer** [comment]
I've started to work on new implementation of Mythic + module, but it isn't yet ready. As the issue needs to be fixed asap, i'll push a temporary fix in waiting.

**Comment by Skamer** [comment]
The fix is now live. 
Take note the dungeon picture isn't fixed, i planned to do it in the new implementation.
