### ISSUE TITLE
Attempt to index global: A nil value

### ISSUE THREAD

**Issue by AussieEevee** [Skamer/Eska-Tracker#12]
**Describe the bug**
This error message appeared in BugSack's backlog.

**Do you have an error log of what happened?**
5x ...aceEskaTracker_Objectives\Modules\Quests.lua:115: attempt to index global '_QuestBlock' (a nil value)
Scorpio\Core.lua:380: in function <Scorpio\Core.lua:375>
(tail call): ?

**To Reproduce**
I don't know what triggered it, as I was just running around Stormwind and wasn't questing or doing anything. It may have even happened on login.

**What is the version of EskaTracker you use ?**
1.0.18

**What are the versions of PLoop and Scorpio you use ?**
(You can known that in opening the EskaTracker options)
- PLoop: 223
- Scorpio: 22

**Additional context**

**Comment by Skamer** [comment]
The code causing that, is triggered when you change zone, a quest has been updated or you have selected 'Show only quests in the zone' from options. The more strange here is why '_QuestBlock' is nil at this moment.

I've started to rework each module (sure this includes the Quest module) for applying the API changes by BFA.

**Comment by Skamer** [comment]
It's fixed.
