### ISSUE TITLE
World Quests not tracking as complete

### ISSUE THREAD

**Issue by Kaymoney** [Skamer/Eska-Tracker#13]
World Quests never complete themselves on the tracker, they always show as one step from completion even when the world quest is gone, and it stays that way until you switch zones or get far enough from the WQ. You cannot untrack them/abandon them.

EDIT: This doesn't seem to be the case for all world quests somehow. But definitely the new Darkshore ones, and pvp ones. Maybe an issue with Angry World Quest compatibility?

Using Angry World Quests v0.19.1

No errors reporting back.

![](https://i.imgur.com/7i0JvMR.png)

Using EskaTracker v1.0.19-beta
Using EskaTracker : Objectives v1.0.14-beta
Using PLoop v223
Using Scorpio v023

**Comment by AussieEevee** [comment]
Having a similar problem with bonus quests, where a bonus quest will stay on the tracker even though I'm no where near the location (Such as having a broken isles bonus quest on there while I'm on Draenor)

I'm not using Angry World quests.

**Comment by Skamer** [comment]
I have reworked  the world quests module in the lastest build, so the issue should go away.
