### ISSUE TITLE
Displaying Rules aren't persistent

### ISSUE THREAD

**Issue by sslebedev** [Skamer/Eska-Tracker#16]
* Tracker>Main>DIsplaying Rules.
* Unmark "In Raid"
* Switch to another tab and back
* See only "Display in combat" is unmarked (even if it was marked), other lines are marked and placed in different order

**Comment by AussieEevee** [comment]
I believe he hasn't implemented it yet.

Change it to macro conditionals and use the following code:

`[combat][group:party][group:raid] hide; show`

it'll cause it to be hidden in combat and in raid and party groups.

**Comment by Skamer** [comment]
It's a bug. The options aren't linked to right setting : editing 'Display in Group' will modify the value of 'Display in Combat'.

**Comment by Skamer** [comment]
Fixed
