### ISSUE TITLE
Minimap icon cannot be moved

### ISSUE THREAD

**Issue by sslebedev** [Skamer/Eska-Tracker#17]
... And this is very bad issue, because it can hide other icons, including standard ones

**Comment by Skamer** [comment]
I don't encounter no issue.
The minimap icon isn't handled directly by EskaTracker but by a lib commonly used by others addons.

Have you tried to check with only EskaTracker enabled ?

**Comment by Skamer** [comment]
Without answer since a long time, i close it. You are free to re-open later.
