### ISSUE TITLE
Minimap click to show/hide doesn't work

### ISSUE THREAD

**Issue by NLZ** [Skamer/Eska-Tracker#20]
Clicking on the minimapicon or broker doesnt toggle the visibility of trackers.

**Comment by Skamer** [comment]
The 'Left Click' behavior hasn't implemented, so i'll remove the text about it. 
ATM, i'm thinking on the possibility to make changes on the 'Click' behaviors.  

If you have some idea about that, feel free to post here.

**Comment by NLZ** [comment]
I like the idea of clicking to hide everything (Trackers and Action Bars too). Cant think of anything else atm.
