### ISSUE TITLE
Context menu options empty

### ISSUE THREAD

**Issue by NLZ** [Skamer/Eska-Tracker#21]
Witch the context menu section is being empty in the options, it might make sense to hide it until you add something to it. Depends on how soon do you plan to use it.

**Comment by Skamer** [comment]
I had initially planned to add an option for changing the the orientation of context menu, but it has been canceled when its orientation is became adaptive (in function where is the tracker).

I have also thought about give a way for customizing the context menu by users from options, but it's not something which will be implemented soon.

For the moment, i'll do as you said.
