### ISSUE TITLE
Timers aren't shown on the quest tracker

### ISSUE THREAD

**Issue by AussieEevee** [Skamer/Eska-Tracker#23]
**Describe the bug**
In one of the quests in the pre-patch event on Alliance side, you are given a 2 minute time limit. There is a timer bar that shows up in the default tracker, but doesn't show on this tracker.

**What is the version of EskaTracker you use ?**
1.0.21 

**What are the versions of PLoop and Scorpio you use ?**
(You can known that in opening the EskaTracker options)
- PLoop: 224
- Scorpio: 24

**Additional context**

**Comment by Skamer** [comment]
The quests with timer are rare, so i have quickly forgotten to implement the timer.
Thank you for pointing out it. I'll be able to test that directly, because i haven't done yet the quest.

**Comment by Skamer** [comment]
I close it. It has been implemented.
