### ISSUE TITLE
Quests are not automatically tracking

### ISSUE THREAD

**Issue by AussieEevee** [Skamer/Eska-Tracker#26]
**Describe the bug**
Quests are not automatically tracking.

On my monk, quests I pick up are not automatically added to the tracker. But it works fine on other characters.

**Do you have an error log of what happened?**
No error is generated.

**To Reproduce**
Not sure what causes this, so I don't know how to reproduce it.

**Expected behavior**
I expect quests to be automatically added to the tracker when picked up.

**What is the version of EskaTracker you use ?**
1.0.23

**What are the versions of PLoop and Scorpio you use ?**
(You can known that in opening the EskaTracker options)
- PLoop: 224
- Scorpio: 24

**Additional context**

**Comment by Skamer** [comment]
Have you tried to disable EskaTracker for seeing if the issue still occurs ?

**Comment by AussieEevee** [comment]
It didn't work with the default tracker either. I ran the following command, and it fixed everything.

`/console autoquestwatch 1`

Thanks.
