### ISSUE TITLE
Dungeon timer so big

### ISSUE THREAD

**Issue by AmenitradieDruidin** [Skamer/Eska-Tracker#27]
Hello, I have only one question.
Can you make the dungeon timer smaller? The numbers are so big! See image

![wowscrnshot_080518_180827](https://user-images.githubusercontent.com/39033070/43688527-b8be8e46-98ea-11e8-81d2-f94454163af3.jpg)

**Comment by Skamer** [comment]
I'll give a way for changing some properties about timer (text size and text font).

**Comment by Skamer** [comment]
It's now implemented.
