### ISSUE TITLE
Hide in Dungeons Option

### ISSUE THREAD

**Issue by ZachieBlade** [Skamer/Eska-Tracker#28]
**Is your feature request related to a problem? Please describe.**
Have you ever been like me? Have you been in a raid, and had things hide, but then joined a dungeon and found that they just don't? 

**Describe the solution you'd like**
Similar to Hide in Raid, Hide in Combat, I'd like a Hide in Dungeon button.

**Describe alternatives you've considered**
I currently have it set to Hide in Group, but it's an imperfect band-aid.

**Comment by AussieEevee** [comment]
On that note, I'd also like to see a battleground option too.

**Comment by ZachieBlade** [comment]
Hide in Arena would be BG, right?
On 6 Aug 2018, 12:53 PM +1000, AussieEevee <notifications@github.com>, wrote:

On that note, I'd also like to see a battleground option too.

**Comment by Skamer** [comment]
I'll add that.

**Comment by Skamer** [comment]
I have some update. 
While i was adding that, i have encountered an issue in the order where the condition will be validated compared of others conditions. I can choose the order but it may be not suitable for some people. So i have decided to improve the options about displaying rules, in giving you the choice in which order the conditions will be checked. 

I put below an image on what i plan to do:
![ekt_newpredefinedmethod](https://user-images.githubusercontent.com/849450/43743297-79583d60-99d5-11e8-8d40-bd3fde71214d.jpg)

Take note it's simply a first iteration. There are things which are not in the image such as :
- Up and Down arrow for controlling the conditions order. 
- A 'Continue' checkbox for each row. If this one is enabled, the next condition will be checked even if the current condition isn't validated.
- An option asking you in which state (hidden or shown) the tracker is if no condition is validated.

I'll ensure the conditions list can be expanded  by plugins and external code.

I have no ETA to give on when things will be finished. 

@ZachieBlade  and @AussieEevee : 
If you want really the conditions now, it can be done with 'Status function' method. I can provide my help at this purpose.

**Comment by Skamer** [comment]
I have finished to create the widgets i need for the options. I put below an image shown the final render:
![ekt_final_displayingrules_render](https://user-images.githubusercontent.com/849450/43789959-87df4544-9a71-11e8-8160-5ff942d3f379.jpg)

Now,  time to link the options to tracker and the database.  If i encounter no issue, you should soon to be able test these new options.

**Comment by Skamer** [comment]
The new options will be included in the next update i plan to deploy tomorrow (Wednesday).

**Comment by AussieEevee** [comment]
I broke it! It only accepted 7, and when I tried to add the 8th, it broke.

<img width="409" alt="2018-08-10 07_04_24-world of warcraft" src="https://user-images.githubusercontent.com/26673976/43930418-d730a01a-9c6b-11e8-8a89-fe41679dd7b9.png">

**Comment by AussieEevee** [comment]
When I reload the UI, I am able to add the 8th, but at the time, it didn't generate the controls to add it before the reload.

**Comment by Skamer** [comment]
This works fine from my side. It occurs each time ?

**Comment by ZachieBlade** [comment]
It happens to me too. Every time, but when I reach 6 & try to add a 7th.

**Comment by Skamer** [comment]
Very strange, i imagine there is no error displayed ?

 I need of your addon configuration. so can you give me the content with a pastebin of this file:
> World of Warcraft / WTF / Account / {Account ID} / SavedVariables / EskaTracker.lua

**Comment by Skamer** [comment]
Ok, i have needed to reach at the 20th to see the issue. I also detect some optimization issues, and can be the origin of initial problem. I'll put a first fix in the next build i'll deploy soon. Others are planned but need more works. i'll also certainly review on how are displayed the conditions (e.g, limited on number displayed at same time with a page system is my first thought).

**Comment by Skamer** [comment]
The version i've deployed before the BFA release improve greatly the options. Have you encountered issues since ?
