### ISSUE TITLE
Untracking a quest causes all entries under it to disappear.

### ISSUE THREAD

**Issue by Latem5** [Skamer/Eska-Tracker#29]
**Describe the bug**
Untracking a quest causes any tracked quests, achievements, etc. under it to disappear, and throws two LUA errors into chat. Additionally, after the errors have occurred, when trying to drag the EskaTracker window around, the quests that were below the now untracked one do not move with the main window.

**Edit:** Abandoning a quest also seems to cause the same issue.

**Do you have an error log of what happened?**
[EskaTracker Error](https://pastebin.com/XGWwftSt)
[PLoop Error](https://pastebin.com/VSTCPnvA)

**To Reproduce**
1. Go to your EskaTracker window.
2. Right-click on a quest.
3. Click 'Untrack' or 'Abandon'
4. See error and attempt to move the EskaTracker window.

**Expected behavior**
I expected the quest to untrack, and everything else to remain.

**Screenshots**
https://i.imgur.com/3u6SZYG.png
https://i.imgur.com/eFyeQga.png

**What is the version of EskaTracker you use ?**
EskaTracker: 1.0.24-beta
EskaObjectives: 1.0.19-beta

**What are the versions of PLoop and Scorpio you use ?**
- PLoop: v224
- Scorpio: v024

**Comment by Skamer** [comment]
I cannot reproduce the issue you encounter, so i need of your addon configuration.  
Can you give me the content with a pastebin of this file:
> World of Warcraft / WTF / Account / {Account ID} / SavedVariables / EskaTracker.lua

**Comment by Latem5** [comment]
https://pastebin.com/TTC4ttrL

**Comment by Skamer** [comment]
Thank you. With your configuration, i can reproduce the issue. I'm working on a fix.

**Comment by Skamer** [comment]
I applied a fix in the **1.0.25**, can you confirm all works fine from you side ?
