### ISSUE TITLE
Continuation of #25

### ISSUE THREAD

**Issue by ZachieBlade** [Skamer/Eska-Tracker#31]
In relation to #25.

I had a quest stay in my tracker even though I removed it from the quest log. It disappeared when I opened the quest log however, so perhaps the information isn't being passed through correctly.

**Comment by Skamer** [comment]
The current fix checks only when there is an update in the quest log, so it's why opening the quest log triggers the fix.  
I'll try an another way, but i'm not 100% sure its works.
