### ISSUE TITLE
Instance quests should get their own block

### ISSUE THREAD

**Issue by AussieEevee** [Skamer/Eska-Tracker#32]
Instance quests (not dungeon quests) are currently placed under the quest block, but the addon recognises them as instance quests, and I'd like to see them get their own block, so I can add them to a different tracker than the main quest tracker.

Example of the quests I mean

<img width="170" alt="2018-08-13 22_29_57-world of warcraft" src="https://user-images.githubusercontent.com/26673976/44038145-a9b487fc-9f48-11e8-9a15-f68f2c0031f9.png">

The two Stormheim quests in this SS.

**Comment by Skamer** [comment]
I love the idea. I'll see if i can implement that before the BFA release, stay tuned !

**Comment by AussieEevee** [comment]
`5x ...aceEskaTracker_Objectives\Modules\Quests.lua:185: attempt to index global '_InstanceQuestBlock' (a nil value)
Scorpio\Core.lua:404: in function <Scorpio\Core.lua:399>
(tail call): ?`

**Comment by Skamer** [comment]
Some change will appear for this feature in the new alpha build should soon be available on curse.  

- I've removed 'Show instance quests in the instance Quest Block' option
- I've added new options for Raid Quest and Dungeon Quest where you can select in which block they will be displayed (Quest Block and Instance Quest Block).

**Comment by Skamer** [comment]
I close the ticket, the feature is now implemented.
