### ISSUE TITLE
Resizing options

### ISSUE THREAD

**Issue by Baramill** [Skamer/Eska-Tracker#39]
I like the visual of this addon but I really hate how small it is. I'd need a method of making it larger to use it.

If there is no way to make is re sizable maybe it can simply get larger every time a quest is added to the tracker up to a limit, then you can scroll down to view the rest (make an option in the settings to show X tracked quests, anything exceeding that must be scrolled to see)

**Comment by Skamer** [comment]
The tracker can be freely resized (width and height) from options. If the content is greater than this height then a scrolling system will appear.

Did it help you or I missed your question ?

**Comment by Baramill** [comment]
I swear I looked all over for the option. I'll give it another once over

**Comment by Skamer** [comment]
It's located in Trackers -> Name of Tracker (e.g, Main) -> General

**Comment by Baramill** [comment]
I feel dumb for not seeing that before lol

Thanks for the quick replies!
