### ISSUE TITLE
Quests not auto tracking

### ISSUE THREAD

**Issue by Diagonet** [Skamer/Eska-Tracker#40]
Describe the bug
When I get a new quest on my alt, it does not track it right away, I need track manualy. On my main its fine. Also, disabling Eskatracker and using blizzard's also tracks normally. (I checked the Cvar for auto tracking and its 1 in all situations described).

What is the version of EskaTracker you use ?
1.0.29-release

What are the versions of PLoop and Scorpio you use ?
(You can known that in opening the EskaTracker options)

    PLoop: 224
    Scorpio: 24

**Comment by Diagonet** [comment]
This seems to only happen if there are no other quests being tracked when you pick you a new one

**Comment by Skamer** [comment]
I've found the issue, the fix will be added in the next build.

Thank for the report

**Comment by Diagonet** [comment]
Don't know if this is the place to say this but I love your addon, its so neat!

**Comment by Skamer** [comment]
Thank you. :)
