### ISSUE TITLE
Profile system not working correct

### ISSUE THREAD

**Issue by SaturosZed** [Skamer/Eska-Tracker#42]
**Describe the bug**
The profile system doesn't work at all.

No matter what I choose as a profile (character, specialization, custom) it's always the same settings. When copying a profile into a custom profile it only gets the font changes, no size or colours.

**Do you have an error log of what happened?**
No lua/xml/whatever error in bugsack

**To Reproduce**
Log into character 1 (Class A, Spec A):
Set your stuff with whatever profile except gobal.
Log into character 2 (Class B, Spec B):
Set your stuff with whatever profile except global and the one for character 1
Log into character 1:
Setup is the same as character 2
Change setup of character 1 again
Log into character 2:
Setup is the same as character 1 now
etc.

**Expected behavior**
Setup should be saved for each profile or even character/specialization as it says.

**Screenshots**
-

**What is the version of EskaTracker you use ?**
1.0.29-release

**What are the versions of PLoop and Scorpio you use ?**
- PLoop: v224
- Scorpio: v024

**Additional context**
Thanks for your hard work :) Best Quest Tracker addon around!

**Comment by Skamer** [comment]
Indeed
There are some issues during the first loading process, caused by the fact the addon struggles for getting the player specialization.
I'm working on that, thank for the report.

**Comment by Skamer** [comment]
The fix will be included in the next build, which should be available soon.
