### ISSUE TITLE
BUG: Tracker Width Reset to Default Every Time I Login or /reload

### ISSUE THREAD

**Issue by add1kted2ka0s** [Skamer/Eska-Tracker#44]
**Describe the bug**
I have resized the width of the Main tracker to 300, but whenever i log in or /reload, the width of the tracker gets sets to the default. Any idea whats causing this, and how I can fix it? It's a minor issue, since I can go to the config and change it, but it's a huge irritant!

**Do you have an error log of what happened?**
None

**To Reproduce**
1. Set the width of the Main tracker to 300
2. Do a /reload
3. See error: Width of the tracker is set to default

**Expected behavior**
The width of the tracker should be 300

**Screenshots**
Gfycat: https://gfycat.com/CleverThickCamel

**What is the version of EskaTracker you use ?**
1.0.29

**What are the versions of PLoop and Scorpio you use ?**
(You can known that in opening the EskaTracker options)
- PLoop: v225
- Scorpio: v024

**Comment by Skamer** [comment]
I'll look, thank for the report. 

Simple question ; Do you use the 'Global' profile ?

**Comment by add1kted2ka0s** [comment]
Yes, I do.

**Comment by killarny** [comment]
I am also seeing this behavior. (Also using the global profile.)

**Comment by Skamer** [comment]
Very nice catch ! It's precisely the value '300' causes issues. If you try others values like '299' or '301', all works fine.

**Comment by Skamer** [comment]
The fix will be included in the next build, which should be available soon.
