### ISSUE TITLE
option to hide individual block headers

### ISSUE THREAD

**Issue by killarny** [Skamer/Eska-Tracker#47]
**Is your feature request related to a problem? Please describe.**
This isn't really a problem per say, but I don't need to have the main quest tracker header showing the label "Quests" all the time (not ever, really).

**Describe the solution you'd like**
It would be nice to be able to disable rendering of the block header on a per-block basis. I don't need to see the Quests block header ever, but I might still like to see the Achievements block header text when I'm tracking one, for example.

**Describe alternatives you've considered**
I did try to make the Quests block header fully transparent, and although I was able to make the background transparent, the text color doesn't have an alpha slider, so I couldn't get it to go away.

However, it would still be better to be able to disable the header entirely, and have it collapse that space down for more content area.

**Comment by Skamer** [comment]
In the next version, you'll be able to disable the header and changing its height. 
![ekt_new_header_option](https://user-images.githubusercontent.com/849450/44904416-8f97b900-ad0f-11e8-907e-281b193fb7c3.jpg)
