### ISSUE TITLE
World Quest List lfg button support

### ISSUE THREAD

**Issue by Hardbunny** [Skamer/Eska-Tracker#49]
**Is your feature request related to a problem? Please describe.**
When using world quest list to track world quests the lfg button does not appear

**Describe the solution you'd like**
A small lfg button next to tracked world quest from the addon: world quest list

**Describe alternatives you've considered**
none

**Additional context**
https://i.imgur.com/dVZPtZp.png

**Comment by Hardbunny** [comment]
Also noticed blizzard's own lfg icons does not show up. Like for example in this wanted quest:
https://i.imgur.com/jDFjEnh.png

Expected behavior:
https://i.imgur.com/qJCir5e.png

**Comment by Skamer** [comment]
The feature of LFG button has been moved in the context menu you can open by a right-click on the quest name.
