### ISSUE TITLE
Non-Interactive Frames

### ISSUE THREAD

**Issue by Diagonet** [Skamer/Eska-Tracker#51]
**Is your feature request related to a problem? Please describe.**
I have one tracker I use to track only WQs, dungeon quests and dungeon completion. I keep it transparent so it only pops up when Im running a dungeon or doing WQs. So when its empty it is an area of my screen that has nothing but doesnt respond to clicks.

**Describe the solution you'd like**
I was hoping to make it click-through since I never have any reason to click on it anyway and sometimes it gets in the way of my fishing. So an option to make a Tracker non-interactive would be awesome!

**Describe alternatives you've considered**
I tried to use "Display Rules" but it is not really the same thing and I did not notice an option to make it show only when it has quests active

**Additional context**
Sorry if I missed this option and it is already available. Thank you for your great addon!

**Comment by Skamer** [comment]
As locked, the tracker should ignore the mouse events and so you should be able click thought it. If this isn't the case, then it's bug.  

About 'Display Rules', i'll look to add the following conditions:
- There is a quest.
- There is a world quest.
- There is a instance quest (raid & dungeon quest).
- There is a bonus objective.

**Comment by AussieEevee** [comment]
I was having a problem with being unable to click through locked frames too. I've taken to disabling my achievement tracker when not actively working on achievements.

**Comment by Skamer** [comment]
Ok, my bad. 
The 'click through it' isn't here while the tracker is locked, which isn't intended. I'll push a fix today.

**Comment by Diagonet** [comment]
Thank you very much! That was a really fast fix

**Comment by Skamer** [comment]
I close the ticket as the issue is fixed.

About new conditions i talked previously, this should come in the next version of EskaTracker : Objectives. I have not ETA to give, like this needs to wait that i finish the rewards for world quests.
