### ISSUE TITLE
When you track a quest that has a long "content" field, the text goes out of boundaries.

### ISSUE THREAD

**Issue by ohyou** [Skamer/Eska-Tracker#57]
**Steps to reproduce the behavior**
1. Accept a quest that has a long content text
2. Start tracking such a quest
3. See the content going out of boundaries

**Expected behavior**
The aforementioned quest's content should be aligned properly

**Screenshots**
https://i.imgur.com/k4aDy9n.png

**Versions**
- Core: 1.1.3-release
- Objectives plugin: 1.1.7-release
- PLoop: v227
- Scorpio: v24

**Additional context**
The issue resolves itself after some time (around 2 minutes) and the contents become aligned again.  
Screenshot: https://i.imgur.com/aF6CAML.png

**Comment by Skamer** [comment]
I'm working on a fix.

Thank for your report.

**Comment by Skamer** [comment]
It's now fixed.
