### ISSUE TITLE
Quest tracker headers disappearing

### ISSUE THREAD

**Issue by FaileDestiny** [Skamer/Eska-Tracker#59]
**Describe the bug**
When I click on the header to maximize the quests (after standing still), the header disappears completely.  It does return after I move for a few seconds, and then I can open the header normally, not sure if this is the idle option or not, as I figured that would remove the box altogether when not interacting with the quest tracker.  But as of yet, have not seen it in action to make any judgements

**Do you have an error log of what happened?**
 No errors

**To Reproduce**
1. Stand Still for a second
2. Click on Quest header

**Expected behavior**
Maximize the quest list

**Screenshots**

**What is the version of EskaTracker you use ?**
1.1.4-release

**What are the versions of PLoop and Scorpio you use ?**
(You can known that in opening the EskaTracker options)
- PLoop: v227
- Scorpio: v24

**Additional context**

**Comment by Skamer** [comment]
I'm not able to reproduce this. Can you make a screen or video for showing the issue ?

**Comment by FaileDestiny** [comment]
This one seems to have been a limited issue.   It hasn't been happening lately with the original toon, or any others.
