### ISSUE TITLE
Support for LookingForGroup as GroupFinder-tool

### ISSUE THREAD

**Issue by Skamer** [Skamer/Eska-Tracker#6]
**Moved from curseforge issues tracker**.
Initially posted by [ben9ty](https://wow.curseforge.com/members/ben9ty)

> As WorldQuestTracker doens't work anymore with 8.0 LookingForGroup seems to be a good replacement: https://www.wowace.com/projects/lookingforgroup

**Comment by Skamer** [comment]
I've not tried yet the addon, but could you say me which features you wish see for the support ?

**Comment by NLZ** [comment]
Cant speak for the original submitter but I think the only thing that can be supported is putting the group finder icon next to each quests.

**Comment by Skamer** [comment]
I decided to not make the support of LookingForGroup.
