### ISSUE TITLE
Infinite loop when viewing 'Status function' display rules

### ISSUE THREAD

**Issue by Graekon** [Skamer/Eska-Tracker#61]
**Describe the bug**
Infinite loop of empty function calls when viewing 'EKT config > Trackers > Main > Display Rules > Status function' and no functions have been defined (this is my first time using this mod).  The looping text is "function() return true endFunction() return true end"

**Do you have an error log of what happened?**
No.  WoW will stop responding and will then crash ("Do you want to close the program or wait" message).  Refer to Step 5 in To Reproduce section, below.

**To Reproduce**
0. Beginning state of the trackers is displayed on screen. All trackers are enabled, but I only have Achievements and Quests at this time.
1. Open 'EskaTracker - Options' (I used /ekt config)
2. Expand 'Trackers'
3. Select 'Main'
4. Select 'Status function'
5. Text will continuously display what appears to be an empty function and will repeat until the WoW client crashes.

**Expected behavior**
N/A.  This is my first time using the mod.

**Screenshots**
N/A.

**What is the version of EskaTracker you use ?**
1.1.6-release

**What are the versions of PLoop and Scorpio you use ?**
(You can known that in opening the EskaTracker options)
- PLoop: v2 3 0
- Scorpio: v2 4

**Additional context**
I would consider this a low priority considering the workaround is to "not do that" for the time being :)

**Comment by Skamer** [comment]
Thank you for reporting it. This will be fixed in the next build which should be available soon.

**Comment by Skamer** [comment]
The best place for posting your questions and comments is the [project page on Curseforge](https://wow.curseforge.com/projects/eskatracker). 

If this concerns only a plugin feature, you may envisaging to go on their respective project page:
- [EskaTracker : Objectives ](https://wow.curseforge.com/projects/eskatracker-objectives)
- [EskaTracker : PetTracker ](https://wow.curseforge.com/projects/eskatracker-pettracker)

ATM, there is no Discord.
