### ISSUE TITLE
wont load at all/ Plood Errors

### ISSUE THREAD

**Issue by Druak** [Skamer/Eska-Tracker#64]
**Describe the bug**
I have the addon and all applicable supporting addons downloaded and when i enter game i have no new tracking panel, im unable to bring up the options panel. though the addons do show in my addon control panel.

**Do you have an error log of what happened?**
i have attached a word document with the 10 LUA errors i received
[Ploop ERRORS.docx](https://github.com/Skamer/Eska-Tracker/files/2742675/Ploop.ERRORS.docx)

**To Reproduce**
Log in??

**Expected behavior**
I excepted the addon to work as ive seen in videos and screenshots.

**Screenshots**
showing that the objective tracker is not working.
![wowscrnshot_010919_152919](https://user-images.githubusercontent.com/46538909/50929787-c4d1b780-1423-11e9-830c-4a9d3d8a19bf.jpg)
Showing that Ploop and Scorpio is downloaded.
![wowscrnshot_010919_152926](https://user-images.githubusercontent.com/46538909/50929788-c56a4e00-1423-11e9-8647-d01856544abe.jpg)
Showing eska tracker is downloaded
![wowscrnshot_010919_152940](https://user-images.githubusercontent.com/46538909/50929789-c56a4e00-1423-11e9-97d8-4cb675c21a12.jpg)
showing that there is no options for the addon in the interface area. also in my chat window you can see the replys at 15:29:14 and :16 to me typing /ekt open and ekt config
![wowscrnshot_010919_153040](https://user-images.githubusercontent.com/46538909/50929791-c56a4e00-1423-11e9-867d-571e979a70d5.jpg)

**What is the version of EskaTracker you use ?**

**What are the versions of PLoop and Scorpio you use ?**
(You can known that in opening the EskaTracker options)
- PLoop: V230(found in twitch)`
- Scorpio: V025(found in Twitch)
Found both in twitch due to not being able to open the options panel in world of warcraft.

**Additional context**

**Comment by Druak** [comment]
I have not tried but ill start testing now.

**Comment by Druak** [comment]
1. Turned off Elvui and it showed up, only showing the pet tracker. wont track a quest
![wowscrnshot_011019_103849](https://user-images.githubusercontent.com/46538909/50983056-2f3a3480-14c4-11e9-875b-f5a229dc922c.jpg)
2. logged out and back in, still shows the pet tracker but wont track a quest.
3. exited game and rolled back scorpion to V024, still not showing tracked quests
![wowscrnshot_011019_104355](https://user-images.githubusercontent.com/46538909/50983271-c3a49700-14c4-11e9-8a9c-199e9b39649a.jpg)
![wowscrnshot_011019_104422](https://user-images.githubusercontent.com/46538909/50983281-c8694b00-14c4-11e9-872f-3a712381d0e9.jpg)

**Comment by Skamer** [comment]
I have just noticed you forgot to install [EskaTracker : Objectives](https://wow.curseforge.com/projects/eskatracker-objectives), this is why you don't see the quests.
