### ISSUE TITLE
Not saving macro conditions between sessions

### ISSUE THREAD

**Issue by AussieEevee** [Skamer/Eska-Tracker#7]
**Describe the bug**
The addon is not saving the contents of the macro conditions between sessions.

**Do you have an error log of what happened?**
Does not appear to be throwing an error.

**To Reproduce**
Create a macro condition for a tracker, accept it. It works fine then log out. Log back in and go back to look at the exact same tracker's macro condition

**Expected behavior**
I expect the macro conditions to save between sessions.

**What is the version of EskaTracker you use ?**
1.0.17

**What are the versions of PLoop and Scorpio you use ?**
(You can known that in opening the EskaTracker options)
- PLoop: 223
- Scorpio: 21

**Additional context**

**Comment by Skamer** [comment]
It's now fixed, Thank you for having reported it.
