### ISSUE TITLE
PetTracker Module does not work

### ISSUE THREAD

**Issue by eTzmNcbkrng** [Skamer/Eska-Tracker#70]
**Describe the bug**
Enabling PetTracker module throws error on login and does not allow compatibility of PetTracker AddOn with Eska as expected.

**Do you have an error log of what happened?**

```
1x ...ns\EskaTracker_PetTracker\EskaTracker_PetTracker-1.0.1-beta.lua:93: attempt to call global '__Hook__' (a nil value)
...ns\EskaTracker_PetTracker\EskaTracker_PetTracker-1.0.1-beta.lua:93: in main chunk

Locals:
(*temporary) = nil
(*temporary) = <table> {
 numFrames = 1
 frameType = "Frame"
 __super = <table> {
 }
 AddSpecie = <function> defined @PetTracker\Components\Tracking\Tracker.lua:65
 frames = <table> {
 }
 AddSpecies = <function> defined @PetTracker\Components\Tracking\Tracker.lua:45
 baseName = "PetTrackerTracker"
 GetColor = <function> defined @PetTracker\Components\Tracking\Tracker.lua:136
 Toggle = <function> defined @PetTracker\Components\Tracking\Tracker.lua:124
 usedFrames = <table> {
 }
 __index = <table> {
 }
 ToggleOptions = <function> defined @PetTracker\Components\Tracking\Tracker.lua:95
 __type = <table> {
 }
 OnCreate = <function> defined @PetTracker\Components\Tracking\Tracker.lua:25
 MaxQuality = <function> defined @PetTracker\Components\Tracking\Tracker.lua:132
 Update = <function> defined @PetTracker\Components\Tracking\Tracker.lua:40
 ShowOptions = <function> defined @PetTracker\Components\Tracking\Tracker.lua:99
}
(*temporary) = "Update"
(*temporary) = "attempt to call global '__Hook__' (a nil value)"
```

**To Reproduce**
Delete (Rename) WTF Folder
Open WoW
Enable following AddOns (and only these AddOns)
```
!BugGrabber
BugSack
EskaTracker
EskaTracker_Objectives
EskaTracker_PetTracker
PLoop
PetTracker
PetTracker_Breeds
PetTracker_Config
PetTracker_Journal
PetTracker_Switcher
PetTracker_Upgrades
Scorpio.MVC
Scorpio.Secure
Scorpio.UI
Scorpio.Widget
Scorpio
```
Log into world
Lua error noted above is immediately thrown

**Expected behavior**
Should have no errors and display Pets in the Eska Quest Tracker

**Screenshots**

**What is the version of EskaTracker you use ?**
1.1.9-release

**What are the versions of PLoop and Scorpio you use ?**
(You can known that in opening the EskaTracker options)
- PLoop: v241
- Scorpio: v026

**Additional context**
As noted above, getting this error with a completely fresh WTF folder.

**Comment by Skamer** [comment]
This is now fixed in the latest version (EskaTracker_PetTracker 1.1.0-release). Take note you need to update first EskaTracker to 1.1.12-release for everything works. 

Sorry for this issue that has lasted so long.
