### ISSUE TITLE
Allow blocks to be part of multiple trackers

### ISSUE THREAD

**Issue by Fraktyl** [Skamer/Eska-Tracker#72]
**Is your feature request related to a problem? Please describe.**
I'd like the ability to have specific trackers for different tasks.

Say I'm doing a Raid, I'd like to have the Instance Quests and also Achievements blocks available.  But I don't want to see tracked Quests at that time.

I'd also like to have the Achievements block available for the main tracker.

Currently blocks can only be assigned to one tracker at a time.

**Describe the solution you'd like**
Ability to have each tracker have the same blocks assigned to it.

**Comment by Skamer** [comment]
Hello, 

This is something i'd like to see in the addon ( a data for multiple view) but unfortunately the way how the addon core  has been designed does this tack will be too difficult to add (there is also high risk to break other things) so this feature won't implemented in the current version.

There are lot of things where i'm not satisfied about the addon such as:
- the options, i don't like them, they are unfriendly and needs a complete revamp.
- like you said it, the block are limited to a one tracker.
-  and others...

This is why i plan to rework (from scratch) the addon.

**Comment by Fraktyl** [comment]
Makes sense.  Appreciate the response!!
