### ISSUE TITLE
GetQuestTagInfo error

### ISSUE THREAD

**Issue by mbarbone1369** [Skamer/Eska-Tracker#73]
Hello,
Love your addon.
Since the new patch was released, your addon gives an error in GetQuestTagInfo(questID) in the Blizzard FrameXML\QuestUtils, in functions in Scorpio, line 72 and 67. 
I have only Eska Tracker enabled, and error will happen when I click icons on the map, or when quests are accepted, or quests are completed, but not turned in, and can also pop up the error when quest is turned in.
![EskaTracker_Error (2)](https://user-images.githubusercontent.com/47456996/66949271-3a5a5c00-f024-11e9-9779-5014bdf05a95.png)

**Comment by Skamer** [comment]
Fixed in the version 1.1.12 of EskaTracker : Objectives. Thanks for having reported it,
