### ISSUE TITLE
Quest Items not interactable.

### ISSUE THREAD

**Issue by Kaymoney** [Skamer/Eska-Tracker#8]
I cannot use quest items from the tracker like I was able to with the original Eska Quest Tracker.
I can hover over them to see their description, but I have to open my bags to use the actual item.

No errors reporting back.

Using Beta version 1.0.18

Using Ploop version 223
Using Scorpio version 021

**Comment by Skamer** [comment]
Hi,
There are some changes about quest items bar. This one isn't created by default, so here the tasks to following for bringing back it. 
1. Go in the **EskaTracker** options.
2. Go in the 'Action Bars' tree category.
3. Create a new 'Action Bar', i call it 'Quest items' from my side.
4. Go in the options of action bar newly created, you can here change these settings.
5. To finish,  you need to link the quest items to this action bar, so go in 'Actions Buttons'
 Tab -> 'Category Mode' then check 'Quest items'.
6. Now, you have your quest items bar, similar you had in **Eska Quest Tracker**.

I'm sorry if it's currently poorly explained at this purpose, i planned to explain that in the FAQ and in the Migration Guide (Eska Quest Tracker -> EskaTracker).

The reason of this change is **EskaTracker** is generic, and must do nothing specific to a content, so this include the quest items. **EskaTracker** provides a generic action bar system where you can link categories (e.g, quest items) to these ones for displaying them. The plugins can create their own categories, the quest items category is created by the plugin **EskaTracker : Objectives**.

I think this should fix your issue, correct me if i'm wrong. I let the ticket open in waiting an answer.

**Comment by Kaymoney** [comment]
Yes, this works. Thank you.

**Comment by Kaymoney** [comment]
The quest item action bar is no longer working, I've tried re-adding it, clicking show/hide button etc.

Using EskaTracker v1.0.19-beta
Using EskaTracker : Objectives v1.0.14-beta
Using PLoop v223
Using Scorpio v023
