### ISSUE TITLE
Auto Quest Tracking

### ISSUE THREAD

**Issue by Sephirithane** [Skamer/Eska-Tracker#80]
**Describe the bug**
For whatever reason, the current beta version doesn't allow for automatic quest tracking. I have to manually go in and turn on quest tracking for each individual quest. I tried the commands below and reloaded my UI and it did not work.
/console autoQuestWatch 1 /console autoQuestProgress 1 

When I disabled the addon and used the default quest tracker it started working again. I tested this on my wife set up on her own PC and she had the same results.

**Do you have an error log of what happened?**
No

**To Reproduce**
Log-in
Pick up a quest
It does not auto track.

**Expected behavior**
I expect the quests to automatically track.

**Screenshots**
N/A

**What is the version of EskaTracker you use ?**
1.5.0-release

**What are the versions of PLoop and Scorpio you use ?**
Ploop v260, Scorpio v053

**Additional context**
N/A

**Comment by Skamer** [comment]
I'm preparing a fix about it.

**Comment by Skamer** [comment]
Fixed
