### ISSUE TITLE
Progress bar achievements are not being properly cleaned up when the achievement is untracked

### ISSUE THREAD

**Issue by AussieEevee** [Skamer/Eska-Tracker#9]
**Describe the bug**
If you untrack a progress bar achievement, then track another achievement, the progress bar remains.

**Do you have an error log of what happened?**
No error is thrown

**To Reproduce**
Track a progress bar achievement, for example "Got my mind on my money" 
Untrack it
Track a non-progress bar achievement (for example duskwood quests)

**Expected behavior**
I expect the progress bar to disappear

**Screenshots**
<img width="139" alt="2018-07-21 04_21_13-world of warcraft" src="https://user-images.githubusercontent.com/26673976/43023546-d1eeb9da-8c9d-11e8-9546-9bddb8245464.png">

**What is the version of EskaTracker you use ?**
1.0.18

**What are the versions of PLoop and Scorpio you use ?**
(You can known that in opening the EskaTracker options)
- PLoop: 21
- Scorpio: 223

**Additional context**

**Comment by Skamer** [comment]
The fix is finished, and will be included in the next build.

**Comment by Skamer** [comment]
I close the ticket, the fix is now live.
